export interface Card {
  id?: string,
  StreetAddress?: string,
  City?: string,
  PostCode?: string,
  Country?: string,
  ClientName?: string,
  ClientEmail?: string,
  ClientStreetAddress?: string,
  ClientPostCode?: string,
  ClientCountry?: string,
  ClientCity?: string,
  InvoiceDate?: string,
  PaymentTerm?: string,
  ProjectDescription?: string,
  ItemName?: string,
  Qty?: string,
  price?: string,
  isPaid?: boolean,
  Total?: number,
}
